=== joelcaples/apache-fop/sample-xsl-xhtml2fo/Howtodevelop-en-2a/dtd/SimpleDoc.dtd
<!--SimpleDoc.dtd

====== SimpleDoc.dtd =============

Version 1.0.0 July 20, 2001 T.Kobayashi, Antenna House, Inc.
Version 1.0.1 July 31, 2001
		ELEMENT icon, ATTLIST name of FIGURE added
Version 1.0.2 Aug. 08, 2001
		Character mnemonic entities added
Version 1.0.3 July 02, 2002
		ELEMENT 'position' added.
====== Preliminary =============

This DTD is designed to be used for simple technical documents, the original design is based on PureSmartDoc.dtd by Tomoharu Asami. The preliminary version was distributed as SampleDoc.dtd at the first "XSL School" held on June 6th, 2001. SampleDoc.dtd was written by T.Makita, Antenna House, Inc.

-->

<!--definition of parameter entities -->

<!ENTITY % inline "a | note | span | figure |b | i | em | code | br | icon | index | underline | ref ">
<!ENTITY % block "p | ul | ol | dl | table | program | pre | div | hidden | fo | bib">

<!-- Character mnemonic entities -->

<!ENTITY % HTMLlat1 PUBLIC
   "-//W3C//ENTITIES Latin 1 for XHTML//EN"
   "xhtml-lat1.ent">
%HTMLlat1;

<!ENTITY % HTMLsymbol PUBLIC
   "-//W3C//ENTITIES Symbols for XHTML//EN"
   "xhtml-symbol.ent">
%HTMLsymbol;

<!ENTITY % HTMLspecial PUBLIC
   "-//W3C//ENTITIES Special for XHTML//EN"
   "xhtml-special.ent">
%HTMLspecial;

<!-- basic attribute sets -->
<!ENTITY  % Attr-com
	"id ID #IMPLIED
	class NMTOKEN #IMPLIED
	style CDATA #IMPLIED
	type NMTOKEN #IMPLIED
	lang NMTOKEN #IMPLIED"
>

<!-- table attribute sets -->

<!ENTITY % cellhalign
	"align      (left|center|right|justify|char) #IMPLIED
	char       CDATA    #IMPLIED
	charoff    CDATA    #IMPLIED"
>


<!ENTITY % cellvalign
	"valign     (top|middle|bottom|baseline) #IMPLIED"
>

<!-- definition of document structure -->

<!ELEMENT  doc ( head , body)>

<!ATTLIST doc %Attr-com;
	toc (true|false) "true"
	cover (true|false) "true"
	toclevel CDATA #IMPLIED
	index (true|false) "true"
>

<!ELEMENT  head (date | author | position | abstract | title)*>

<!ELEMENT date  (#PCDATA | %inline;)*>
<!ATTLIST date %Attr-com;
>

<!ELEMENT  author (#PCDATA | %inline;)*>
<!ATTLIST author %Attr-com;
	logo CDATA #IMPLIED
	pos (upper|side) "upper"
	width CDATA #IMPLIED
	height CDATA #IMPLIED>

<!ELEMENT  position (#PCDATA | %inline;)*>
<!ATTLIST position %Attr-com;
>

<!ELEMENT abstract (#PCDATA | %inline;)*>
<!ATTLIST abstract %Attr-com;
>

<!ELEMENT  title (#PCDATA | %inline;)*>
<!ATTLIST  title %Attr-com;
>

<!ELEMENT body (part | chapter | section | appendix | (%block;) | (%inline;) | newpage)*>


<!ELEMENT  part (title, (chapter | (%block;) | (%inline;) |newpage )*)>
<!ATTLIST part %Attr-com;
	logo CDATA #IMPLIED
>

<!ELEMENT chapter (title, (section | (%block;) | (%inline;) |newpage)*)>
<!ATTLIST  chapter %Attr-com;
	logo CDATA #IMPLIED
>

<!ELEMENT section (title, (subsection | (%block;) | (%inline;) |newpage)*)>
<!ATTLIST section %Attr-com;
	logo CDATA #IMPLIED
>

<!ELEMENT  subsection (title, (subsubsection | (%block;) | (%inline;)| newpage)*)>
<!ATTLIST subsection %Attr-com;
	logo CDATA #IMPLIED
>

<!ELEMENT subsubsection (title, ((%block;) | (%inline;) | newpage)*)>
<!ATTLIST  subsubsection %Attr-com;
	logo CDATA #IMPLIED
>

<!ELEMENT appendix (title, (subsection | bib | (%block;) | (%inline;) |newpage )*)>
<!ATTLIST appendix %Attr-com;
	logo CDATA #IMPLIED
>

<!--definition of block elements-->

<!ELEMENT  p (#PCDATA | %block; | %inline;)*>
<!ATTLIST p %Attr-com;
	align (left | right | center | justify) #IMPLIED
>

<!ELEMENT figure (title?)>
<!ATTLIST  figure %Attr-com;
	src CDATA #REQUIRED
	alt CDATA #IMPLIED
	align CDATA #IMPLIED
	width CDATA #IMPLIED
	height CDATA #IMPLIED
	caption (before | after) "after"
>

<!ELEMENT  ul (li*)>
<!ATTLIST ul %Attr-com;
>

<!ELEMENT ol (li*)>
<!ATTLIST ol %Attr-com;
>

<!ELEMENT bib (li*)>

<!ATTLIST bib %Attr-com;
>

<!ELEMENT  li (#PCDATA | %block; | %inline;)*>
<!ATTLIST li %Attr-com;
>

<!ELEMENT dl ((dt, dd)*)>
<!ATTLIST dl %Attr-com;
>

<!ELEMENT  dt (#PCDATA | %block; | %inline;)*>
<!ATTLIST dt %Attr-com;
>

<!ELEMENT dd (#PCDATA | %block; | %inline;)*>
<!ATTLIST dd %Attr-com;
>

<!-- definition of table -->

<!ELEMENT  table (title?, col*, thead?, tfoot?, tbody)>
<!ATTLIST table %Attr-com;
	layout (auto | fixed) "auto"
	align (left | center | right) "left"
	width CDATA #IMPLIED
	rowheight CDATA #IMPLIED
	border NMTOKEN #IMPLIED
	summary CDATA #IMPLIED
	cellspacing CDATA #IMPLIED
	cellpadding CDATA #IMPLIED
	rules (none | groups | rows | cols | all ) "all"
	frame (void | above | below | hsides | lhs | rhs | vsides| box | border) "border"
	caption (before | after | start | end ) #IMPLIED
>

<!ELEMENT  col EMPTY>
<!ATTLIST col %Attr-com;
	number CDATA #IMPLIED
	width CDATA #IMPLIED
>

<!ELEMENT  thead (tr*)>
<!ATTLIST thead %Attr-com;
	height CDATA #IMPLIED
	%cellhalign;
	%cellvalign;
>

<!ELEMENT  tfoot (tr*)>
<!ATTLIST tfoot %Attr-com;
	%cellhalign;
	%cellvalign;
>

<!ELEMENT  tbody (tr*)>
<!ATTLIST tbody %Attr-com;
	%cellhalign;
	%cellvalign;

>

<!ELEMENT  tr (th | td)*>
<!ATTLIST tr %Attr-com;
	height CDATA #IMPLIED
	%cellhalign;
	%cellvalign;
>

<!ELEMENT  th  (#PCDATA | %block; | %inline;)*
>
<!ATTLIST th %Attr-com;
	rowspan CDATA #IMPLIED
	colspan CDATA #IMPLIED
	%cellhalign;
	%cellvalign;
>

<!ELEMENT  td (#PCDATA | %block; | %inline;)*>
<!ATTLIST td %Attr-com;
	rowspan CDATA #IMPLIED
	colspan CDATA #IMPLIED
	%cellhalign;
	%cellvalign;
>

<!ELEMENT  program (#PCDATA | title)*>
<!ATTLIST program %Attr-com;
>

<!ELEMENT pre (#PCDATA)>

<!ELEMENT  div (#PCDATA | title| %block; | %inline;)*>
<!ATTLIST div %Attr-com;
	border ( auto | none) "auto"
>

<!--definition of inline elements -->

<!ELEMENT  a (#PCDATA | %inline;)*>
<!ATTLIST a %Attr-com;
	name CDATA #IMPLIED
	href CDATA #IMPLIED
>
<!ELEMENT icon EMPTY><!ATTLIST 	icon %Attr-com;
	src CDATA #REQUIRED
>


<!ELEMENT  note (#PCDATA | %inline;)*>
<!ATTLIST note %Attr-com;
>

<!ELEMENT span (#PCDATA | %inline;)*>
<!ATTLIST span %Attr-com; 
>

<!ELEMENT  b (#PCDATA | %inline;)*>
<!ATTLIST b %Attr-com;
>

<!ELEMENT i (#PCDATA | %inline;)*>
<!ATTLIST i %Attr-com;
>

<!ELEMENT  em (#PCDATA | %inline;)*>
<!ATTLIST em %Attr-com;
>

<!ELEMENT code (#PCDATA | %inline;)*>
<!ATTLIST code %Attr-com;
font CDATA #IMPLIED
>

<!ELEMENT index (#PCDATA | index)*>
<!ATTLIST index
key CDATA #IMPLIED
keyword CDATA #IMPLIED
>
<!ELEMENT  underline (#PCDATA | %inline;)*>
<!ATTLIST underline %Attr-com;
>
<!-- special element for reference -->

<!ELEMENT ref EMPTY>
<!ATTLIST ref ref-id IDREF #REQUIRED
>

<!-- special element to control page break -->

<!ELEMENT  newpage EMPTY>

<!-- special element to control line break -->

<!ELEMENT br EMPTY>

<!-- special element to prohibit content of element to be shown. -->

<!ELEMENT  hidden ANY>

<!-- for XSL-FO block -->
<!ELEMENT fo (#PCDATA)>

=== joelcaples/apache-fop/sample-xsl-xhtml2fo/Howtodevelop-en-2a/xml/Howtodevelop-en-2a.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE doc SYSTEM "../dtd/SimpleDoc.dtd">
<doc toc="true" toclevel="3" cover="true" xmlns:fo="http://www.w3.org/1999/XSL/Format" lang="en">
<head>
<date>July, 2005<br/>2nd Edition</date>
<author logo="img/ahlogo.svg" width="41.54mm" height="8.73mm">Antenna House, Inc.<br/>Copyright &#x00a9; 2001-2007 Antenna House, Inc.</author>
<abstract>This tutorial explains the way to edit XSL stylesheet that transforms XML document file into XSL-FO.</abstract>
<title>How to Develop Stylesheet<br/>for XML to XSL-FO Transformation</title>
</head>
<body>
<section logo="img/ico4.png">
<title>Preface</title>
<p>
Extensible Stylesheet Language (XSL)<ref ref-id="a1"/> has been brought to the attention of a wide audience as a specification recommended by W3C on 15th October, 2001 for displaying and printing the XML document. The following is the general process to transform the XML document into XSL Formatting Objects (XSL-FO) and print it.
</p>
<ol>
<li>Develop the stylesheet that conforms to the DTD of the source XML document to create the target output.</li>
<li>Input the XML document and the XSL stylesheet to the XSLT processor to create XSL-FO.</li>
<li> Get the target outputs such as paper-based output, PDF output, by the XSL-FO processor.</li>
</ol>
<p/>
<figure src="img/XSL-FO_proc.emf">
<title>Generating XSL-FO and Display/Print by XSL Formatter</title>
</figure>
<p>
The knowledge about XSLT and XSL is necessary to develop XSLT stylesheet. The knowledge about XSLT and XSL is necessary to develop XSLT stylesheet. As for XSLT, many reference books has been published other than the specification<ref ref-id="a2"/>.
Probably, XSLT is already much more familiar one, since it is often used for the conversion from XML to HTML.
The XSL specification <ref ref-id="a1"/>has a huge amount of contents, it has over 400 pages. It is pretty hard to understand this specification. But basically it is intended for implementers. It is not necessary for XSLT stylesheet designers to understand everything. You can fully write stylesheet by knowing some regular contents and patterns.
</p>
<p>
This report explains how to edit stylesheet which is used for transforming XML documents into XSL-FO according to the example of <index>SimpleDoc</index>. SimpleDoc is made for this report as a format to write a simple document. This is based on <index>PureSmartDoc</index>
<ref ref-id="a4"/> presented by Tomoharu Asami.
To make it a simple, the number of the elements is reduced and the useful functions for writing and formatting documents are added.
</p>
<p>This report explains how to edit a stylesheet which is used for transforming a SimpleDoc document into XSL-FO. This report itself is the instance XML document of SimpleDoc.dtd, and it is then ready to be formatted by Antenna House <index>XSL Formatter</index> with the stylesheet which transforms the SimpleDoc document explained here into XSL-FO.
</p>
</section>
<section logo="img/ico4.png">
<title>Step for XSL-FO Transformation </title>
<p>Now, what steps are necessary to develop XSL stylesheet?  These steps are explained briefly as below.</p>
<table layout="fixed">
<col number="1" width="30%"/>
<col number="2" width="70%"/>
<thead>
<tr>
<th align="center">Steps</th>
<th align="center">Contents</th>
</tr>
</thead>
<tbody>
<tr>
<td>
Know the structure of the XML document</td>
<td>First, the information about the structure of XML source documents is required. XSLT processor can transform XML document into XSL-FO without a DTD. But the information described in the DTD such as types of elements, contents of elements, appearing order of elements and values of properties are necessary for developing a stylesheet.

</td>
</tr>
<tr>
<td>Specify a printing form
</td>
<td>
This is the printing form as a final output, in other words the output specification. XSL is a formatting specification.  Printing forms has various range of specifications such as sizes and layouts of printing paper, layouts of head and body, deciding whether or not to output index, table of contents, and so on.
</td>
</tr>
<tr>
<td>Apply a printing form to formatting objects</td>
<td>After determining the specification of printing, you have to know what XSL formatting objects and properties are applied in order to print in this style. It is better to practice how to specify by referring to a simple stylesheet. </td>
</tr>
<tr>
<td>Develop an XSL stylesheet</td>
<td>Put the instructions to the stylesheet in order to transform XML source documents into the target printing form. Map the XML source document to XSL formatting objects that can generate the output specification. The stylesheet have the similar aspect as the general programming languages, while it may be difficult if you do not understand the feature of the XSL.  <note>Refer to the definition list template in this report. In XSL, Structure for control of the conditional branch can be made, but it is impossible to assign a value to a variable. The technique to realize by calling loops recursively is necessary.</note>
</td>
</tr>
</tbody>
</table>
</section>
<section logo="img/ico4.png">
<title>SimpleDoc Organization
</title>
<p>
The following table shows the structure of SimpleDoc treated in this report. For more detail, refer to SimpleDoc.dtd.</p>
<table rowheight="2em">
<col number="1" width="17.5%"/>
<col number="2" width="22.5%"/>
<col number="3" width="60%"/>
<thead>
<tr height="1em">
<th> Element</th>
<th> Meaning</th>
<th>Definition</th>
</tr>
</thead>
<tbody>
<tr>
<td>
a group of block elements
</td>
<td>&#x2014;</td>
<td>p | figure | ul | ol | dl | table | program | div</td>
</tr>
<tr>
<td>

a group of inline elements
<br/>
</td>
<td>&#x2014;</td>
<td>a | note | span | b | i | em | code | br
</td>
</tr>
<tr>
<td>doc<br/>
</td>
<td> root element </td>
<td>(head, body)</td>
</tr>
<tr>
<td>head<br/>
</td>
<td> header</td>
<td>(date | author | abstract | title)*</td>
</tr>
<tr>
<td>date, author, abstract, title<br/>
</td>
<td> header elements,<br/> date, author, abstract, title</td>
<td>
(#PCDATA | a group of inline elements)*
</td>
</tr>
<tr>
<td>body</td>
<td> body</td>
<td>
(chapter | part | section | a group of block elements | a group of inline elements)*
</td>
</tr>
<tr>
<td>part</td>
<td>part</td>
<td>(title, (chapter |a group of block elements | a group of inline elements)*)</td>
</tr>
<tr>
<td>chapter</td>
<td>chapter</td>
<td>(title, (section | a group of bock elements | a group of inline elements)*)
</td>
</tr>
<tr>
<td>section</td>
<td> section</td>
<td>(title, (subsection | a group of block elements | a group of inline elements)*)
</td>
</tr>
<tr>
<td>subsection</td>
<td> subsection</td>
<td>
(title, (subsubsection | a group of block elements | a group of inline elements)*)
</td>
</tr>
<tr>
<td>subsubsection</td>
<td>subsubsection</td>
<td>
(title, (a group of block elements | a group of inline elements)*)
</td>
</tr>
<tr>
<td>title</td>
<td> title</td>
<td>
(#PCDATA | a group of inline elements)*
</td>
</tr>
<tr>
<td>p<br/>
</td>
<td> paragraph</td>
<td>
(#PCDATA | a group of block elements | a group of inline elements)*

</td>
</tr>
<tr>
<td>figure<br/>
</td>
<td>figure</td>
<td>(title?)<br/>
Specify a file by the src property.</td>
</tr>
<tr>
<td>ul<br/>
</td>
<td>
unordered list

</td>
<td>(li*)<br/>
Specify a character for label of line by the type property.

</td>
</tr>
<tr>
<td>ol<br/>
</td>
<td>
ordered list </td>
<td>(li*)<br/>
Specify format of number in the label by the type property.
</td>
</tr>
<tr>
<td>dl<br/>
</td>
<td>
definition list</td>
<td>(dt, dd)*<br/>
Specify whether to format the block in horizontal way or in vertical way by the type property.
</td>
</tr>
<tr>
<td>dt<br/>
</td>
<td>
definition term
</td>
<td>(#PCDATA | a group of block elements | a group of inline elements)*
</td>
</tr>
<tr>
<td>dd<br/>
</td>
<td>description of details
</td>
<td>
(#PCDATA | a group of block elements | a group of inline elements)*
</td>
</tr>
<tr>
<td>table<br/>
</td>
<td>
entire table
</td>
<td>(title?, col*, thead?, tfoot?, tbody)<br/>
Specify whether to make auto layout or fixed by the layout property. Specify the width of the entire table by the width property.
</td>
</tr>
<tr>
<td>col<br/>
</td>
<td>
column format
</td>
<td>EMPTY<br/>
Speciry the number of the column by the number property, the width of the column by the width property.
</td>
</tr>
<tr>
<td>thead</td>
<td>
table header
</td>
<td>(tr*)</td>
</tr>
<tr>
<td>tfoot</td>
<td>
table footer
</td>
<td>(tr*)</td>
</tr>
<tr>
<td>tbody</td>
<td>table body
</td>
<td>(tr*)</td>
</tr>
<tr>
<td>tr</td>
<td>
table row</td>
<td>(th | td)*<br/>Specify the height of the row by the height property.</td>
</tr>
<tr>
<td>th</td>
<td>
table header
</td>
<td>(#PCDATA | a group of inline elements | a group of block elements)*<br/>
Specify the number of the columns to be expanded across, the number of the rows to be expanded vertically by the colspan and rowspan properties. The align property allows horizontal alignment to be set to left, right, or center. The valign property allows vertical alignment to be set to top, middle, bottom or baseline.
</td>
</tr>
<tr>
<td>td</td>
<td>
table data
</td>
<td>(#PCDATA | a group of inline elements | a group of block elements)*<br/>

Specify the number of the columns to be expanded across, the number of the rows to be expanded vertically by the colspan and rowspan properties. The align property allows horizontal alignment to be set to left, right, or center. The valign property allows vertical alignment to be set to top, middle, bottom or baseline.</td>
</tr>
<tr>
<td>program</td>
<td>
program code
</td>
<td>(#PCDATA | title)*</td>
</tr>
<tr>
<td>div</td>
<td>general block element
</td>
<td>
(title, (general block element | general inline element)*)
<br/>
The div element expands the type by the class property.
</td>
</tr>
<tr>
<td>a<br/>
</td>
<td>
anchor(link)
</td>
<td>(#PCDATA | a group of inline elements)*
